<?php

namespace App\Models;

use App\Models\Localizacao\Comite;
use App\Models\Localizacao\Municipio;
use App\Models\Localizacao\Provincia;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Membro extends Model
{


    use HasFactory;
    protected $fillable = ['nome', 'email', 'telefone', 'sexo', 'data_nascimento', 'municipio','comuna_id',
        'comuna', 'provincia', 'bi', 'pai', 'mae', 'mae', 'ano_ingresso', 'onde_ingressou', 'numero_membro',
        'cartao_municipe', 'comite_id', 'estrutura', 'foi_militar', 'scope'];


protected static function boot()
{
    parent::boot(); // TODO: Change the autogenerated stub

   static::addGlobalScope('municipio', function ($query) {
        $user = auth()->user();
        if ($user->abragencia == 'municipal'){
            $query->where('scope', $user->scope);
        }
   });
}

    public function orgaos() {
        return $this->belongsToMany(Orgao::class,
            'membro_orgaos',
            'membro_id',
            'orgao_id'
        );
    }

    public function funcoes () {
        return $this->belongsToMany(Funcao::class,
            'funcao_membros',
            'membro_id',
            'funcao_id'
        );
    }

    public function nucleo () {
        return $this->belongsTo(Comite::class, 'comite_id');
    }


}
